-- Stores scripts needed for development (dummy) data

INSERT INTO contribution_index_schema."RD_Schedule_Memb_Status"
    ("schdl_memb_status_code", "schdl_memb_status_desc", "record_start_date", "record_end_date", "updated_by",  "created_by", "last_updated_timestamp" ) VALUES  ('MS1', 'To be reviewed', NOW(), NOW(), 'System', 'System', NOW()), ('MS2', 'Ready to submit', NOW(), NOW(), 'System', 'System', NOW()),('MS3', 'Action needed', NOW(), NOW(), 'System', 'System', NOW()),('MS4', 'Submitted', NOW(), NOW(), 'System', 'System', NOW()),('MS5', 'Processing payment', NOW(), NOW(), 'System', 'System', NOW()),('MS6', 'Paid', NOW(), NOW(), 'System', 'System', NOW()),('MS7', 'Payment Failed', NOW(), NOW(), 'System', 'System', NOW()
);

INSERT INTO contribution_index_schema."RD_Schedule_Status"
    ("schedule_status_code", "schedule_status_desc", "record_start_date", "record_end_date", "updated_by",  "created_by", "last_updated_timestamp" ) VALUES  ('CS1', 'New schedule', NOW(), NOW(), 'System', 'System', NOW()), ('CS2', 'Attention Needed', NOW(), NOW(), 'System', 'System', NOW()),('CS3', 'Ready to Submit', NOW(), NOW(), 'System', 'System', NOW()),('CS4', 'Submitted', NOW(), NOW(), 'System', 'System', NOW()),('CS5', 'Partially Submitted', NOW(), NOW(), 'System', 'System', NOW()),('CS6', 'Payment needed', NOW(), NOW(), 'System', 'System', NOW()),('CS7', 'Processing payment', NOW(), NOW(), 'System', 'System', NOW()),('CS8', 'Paid', NOW(), NOW(), 'System', 'System', NOW()),('CS9', 'Partially paid', NOW(), NOW(),  'System', 'System', NOW()),('CS10', 'Payment failed', NOW(), NOW(),  'System', 'System', NOW()),('CS11', 'Deleted', NOW(), NOW(),  'System', 'System', NOW()),('CS12', 'Overdue', NOW(), NOW(),  'System', 'System', NOW()
);

INSERT INTO contribution_index_schema."RD_Part_Contrib_Reason"
    ("reason_code", "reason_description", "record_start_date", "record_end_date", "updated_by",  "created_by", "last_updated_timestamp" ) VALUES  ('CON01', 'Member is temporarily absent', NOW(), NOW(), 'System', 'System', NOW()), ('CON02', 'Member is on Family Leave', NOW(), NOW(), 'System', 'System', NOW()),('CON05', 'Meeting Member Duties Elsewhere', NOW(), NOW(), 'System', 'System', NOW()),('CON07', 'Withheld as within Opt Out Period', NOW(), NOW(), 'System', 'System', NOW()),('CON09', 'Processing payment', NOW(), NOW(), 'Adhoc Late Contribution', 'System', NOW()),('CON10', 'No Further Contributions Payable', NOW(), NOW(), 'System', 'System', NOW()),('CON11', 'Member stopped contributions', NOW(), NOW(), 'System', 'System', NOW()),('CON12', 'Member has Insufficient Earnings', NOW(), NOW(), 'System', 'System', NOW()),('CON13', 'Transferring Member to a Different Payment Source', NOW(), NOW(), 'System', 'System', NOW()),('CON14', 'Change Member Groups and Pay Contributions', NOW(), NOW(), 'System', 'System', NOW()),('CON15', 'Pay for Previous and New Group', NOW(), NOW(), 'System', 'System', NOW()),('CON16', 'Member has Opted Out', NOW(), NOW(), 'System', 'System', NOW()),('CON17', 'Pay For More Than 1 Enrolment', NOW(), NOW(), 'System', 'System', NOW()),('CON18', 'Change of Payment Source and Group', NOW(), NOW(), 'System', 'System', NOW()
);